#include <stdio.h>
#include <stdlib.h>
#include <amd_comgr.h>

void checkError(amd_comgr_status_t , char*);
int disassembler(const char*, const char*, const char*);

int main(int argc, char** argv) 
{
    if (argc < 4) 
    {
        printf("Usage : amd-disassembler <.hsaco> <isa_name> <output_file>\n");
        printf("<.hsaco> can be generated by specify following env var before executing HIP/OpenCL app:\n");
        printf("export LOADER_OPTIONS_APPEND=\"-dump-code=1 -dump-dir=<path/to/save/dump>\"\n");
        exit(EXIT_FAILURE);
    }
    disassembler(argv[1], argv[2], argv[3]);

    printf("> Assembly file saved to %s\n", argv[4]);
    return 0;
}

void checkError(amd_comgr_status_t statue, 
               char* error_msg)
{
    if (statue != AMD_COMGR_STATUS_SUCCESS)
    {
        printf("> AMD-Disassember Error %d : %s\n", statue, error_msg);
        exit(EXIT_FAILURE);
    }
}

int disassembler(const char*          hsaco_file, 
                 const char*          isa_name, 
                 const char*          output_file)
{
    FILE*        binary_file     = NULL;
    FILE*        assembly_file   = NULL;
    char*        binary_buffer   = NULL;
    char*        assembly_buffer = NULL;
    unsigned int binary_size     = 0;
    size_t       assembly_size   = 0;

    amd_comgr_status_t      status;
    amd_comgr_action_info_t action;
    amd_comgr_data_set_t    binary;
    amd_comgr_data_t        data;
    amd_comgr_data_set_t    disassembly;
    amd_comgr_data_t        disassembly_data;

    binary_file = fopen(hsaco_file, "rb");
    if (binary_file == NULL)
    {
        printf("> AMD-Disassember Error : Cannot open %s\n", hsaco_file);
        exit(EXIT_FAILURE);
    }
    else
    {
        fseek(binary_file, 0, SEEK_END);
        binary_size = ftell(binary_file);
        fseek(binary_file, 0, SEEK_SET);
        binary_buffer = (char*) malloc(sizeof(char) * binary_size);
        fread((void*)binary_buffer, 1, binary_size, binary_file);
        fclose(binary_file);
    }

    status = amd_comgr_create_action_info(&action);
    checkError(status, "create action");
    status = amd_comgr_action_info_set_isa_name(action, isa_name);
    checkError(status, "set isa name");
    status = amd_comgr_create_data_set(&binary);
    checkError(status, "create data set");
    status = amd_comgr_create_data(AMD_COMGR_DATA_KIND_EXECUTABLE, &data);
    checkError(status, "create data");
    status = amd_comgr_set_data(data, binary_size, binary_buffer);
    checkError(status, "set data");
    status = amd_comgr_set_data_name(data, "kernel");
    checkError(status, "set data name");
    status = amd_comgr_data_set_add(binary, data);
    checkError(status, "data set add");
    status = amd_comgr_create_data_set(&disassembly);
    checkError(status, "create data set");
    status = amd_comgr_do_action(AMD_COMGR_ACTION_DISASSEMBLE_EXECUTABLE_TO_SOURCE , action, binary, disassembly);
    checkError(status, "do action");
    status = amd_comgr_create_data(AMD_COMGR_DATA_KIND_SOURCE, &disassembly_data);
    checkError(status, "create disassembly data ");
    status = amd_comgr_action_data_get_data(disassembly, AMD_COMGR_DATA_KIND_SOURCE, 0, &disassembly_data);
    checkError(status, "action get disassembly data ");
    status = amd_comgr_get_data(disassembly_data, &assembly_size, NULL);
    checkError(status, "get disassembly data size");
    assembly_buffer = (char*) malloc(sizeof(char) * assembly_size);
    status = amd_comgr_get_data(disassembly_data, &assembly_size, assembly_buffer);

    assembly_file = fopen(output_file, "w");
    if (assembly_file == NULL)
    {
        printf("> AMD-Disassember Error : Cannot open %s\n", output_file);
        exit(EXIT_FAILURE);
    }
    else
    {
        fwrite(assembly_buffer, 1, assembly_size, assembly_file);
        fclose(assembly_file);
    }
    
    free(binary_buffer);
    free(assembly_buffer);
    return 0;
}